### ISSUE TITLE
php artisan queue:work 报错

### ISSUE THREAD

**Issue by qusheng19890714** [freyo/laravel-queue-rocketmq#3]
lumen5.5版本。报错  No connector for [rocketmq]

**Comment by freyo** [comment]
请检查配置文件 config/queue.php

**Comment by qusheng19890714** [comment]
还有个问题，阿里云的ackMessage接收的是一个数组， 现在是传的字符串，导致应答不成功

**Comment by freyo** [comment]
1.0.1 fixed
