### ISSUE TITLE
如何监听多个topic

### ISSUE THREAD

**Issue by qusheng1989** [freyo/laravel-queue-rocketmq#4]
请教下，如何监听多个topic，谢谢

**Comment by qusheng1989** [comment]
/**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        if ($this->app instanceof LumenApplication) {
            $this->app->configure('queue');
        }

        $this->mergeConfigFrom(
            __DIR__.'/../config/rocketmq.php', 'queue.connections.rocketmq'
        );
    }

    /**
     * Register the application's event listeners.
     *
     * @return void
     */
    public function boot()
    {
        /** @var QueueManager $queue */
        $queue = $this->app['queue'];

        $queue->addConnector('rocketmq', function () {
            return new RocketMQConnector();
        });
    }


我需不需要改这个

**Comment by freyo** [comment]
消费队列消息？php artisan queue:work {connection-name} --queue={queue-name}
